### ISSUE TITLE
Trying the save command, didn't work

### ISSUE THREAD

**Issue by Shraneid** [360modder/vsdownload#2]
Hey, was trying your soft because I'd like to download an m3u8 file (didn't know that existed 2hrs ago) and encountered an issue

```
INFO: segment 2426 added to retry queue 11
INFO: segment 2427 added to retry queue 11
INFO: segment 2428 added to retry queue 11
INFO: segment 2429 added to retry queue 11
INFO: segment 2430 added to retry queue 11
INFO: segment 2431 added to retry queue 11
INFO: segment 2432 added to retry queue 11
INFO: segment 2433 added to retry queue 11
INFO: segment 2434 added to retry queue 11
INFO: segment 2435 added to retry queue 11
INFO: segment 2436 added to retry queue 11
INFO: segment 2437 added to retry queue 11
INFO: segment 2438 added to retry queue 11
INFO: segment 2439 added to retry queue 11
INFO: segment 2440 added to retry queue 11
INFO: segment 2441 added to retry queue 11
INFO: segment 2442 added to retry queue 11
INFO: segment 2443 added to retry queue 11
INFO: segment 2444 added to retry queue 11
```
Here are the logs output, it keeps putting every segment into retry for some reason 

The command I used which can probably reproduce the error
```
vsdownload.exe save https://s1.streami.cool/files/11891/output.m3u8 -o test.mp4
```

Cheers :)

**Comment by clitic** [comment]
Maybe your internet connection is weak. You can try to reduce default thread count by using `-t 2` flag. Also note [vsdownload](https://github.com/clitic/vsdownload) is deprecated you should use https://github.com/clitic/vsd instead. Here are some screenshots from new vsd.

![command](https://user-images.githubusercontent.com/71246790/193499363-884b9056-ee8b-4155-bdef-cc64041df5cd.png)

![player](https://user-images.githubusercontent.com/71246790/193499377-b7c71dc3-cdc0-4c3c-9890-ad1bcd94a5e8.png)
