### ISSUE TITLE
'NoneType' object has no attribute 'replace'

### ISSUE THREAD

**Issue by AliAtes** [360modder/vsdownload#3]
┌─────────────────────────────── Traceback (most recent call last) ────────────────────────────────┐
│ C:\Users\ATES-PC\anaconda3\lib\site-packages\vsdownload\vsdownload.py:51 in call_save            │
│                                                                                                  │
│   48 │   │   timeout: int = typer.Option(5, help="waiting time for post tasks to perform afte    │
│   49 │   │   pre_select: int = typer.Option(None, help="pre select a url from log.json file",    │
│   50 │   ):                                                                                      │
│ > 51 │   command_save(Namespace(**locals()))                                                     │
│   52                                                                                             │
│   53 def capture(                                                                                │
│   54 │   │   url: str, driver: str, output: str = "log.json", scan_ext: str = "ts", baseurl:     │
│                                                                                                  │
│ ┌─────────────────────────────────────────── locals ───────────────────────────────────────────┐ │
│ │       baseurl = None                                                                         │ │
│ │    chunk_size = 1024                                                                         │ │
│ │       cleanup = True                                                                         │ │
│ │       decrypt = True                                                                         │ │
│ │   ffmpeg_path = 'ffmpeg'                                                                     │ │
│ │       headers = None                                                                         │ │
│ │         input = 'https://btk-cdn01.cinema8.com/hls/content/entry/data/0/38/0_htzs22hi_0_lid… │ │
│ │        key_iv = None                                                                         │ │
│ │   max_quality = False                                                                        │ │
│ │        output = 'merged.ts'                                                                  │ │
│ │    pre_select = None                                                                         │ │
│ │ proxy_address = None                                                                         │ │
│ │   retry_count = 10                                                                           │ │
│ │       tempdir = 'temptsfiles'                                                                │ │
│ │       threads = 5                                                                            │ │
│ │       timeout = 5                                                                            │ │
│ │       verbose = False                                                                        │ │
│ └──────────────────────────────────────────────────────────────────────────────────────────────┘ │
│                                                                                                  │
│ C:\Users\ATES-PC\anaconda3\lib\site-packages\vsdownload\commands\save.py:477 in command_save     │
│                                                                                                  │
│   474 │   segments = m3u8_downloader.parse_m3u8(parsed_links)                                    │
│   475 │   print(f"file will be saved at: {args.output}")                                         │
│   476 │   print(f"starting download in {args.threads} thread/s\n")                               │
│ > 477 │   m3u8_downloader.download_in_mutiple_thread(segments, parsed_links)                     │
│   478 │   console.print(f"\n[green]file downloaded successfully at: {args.output}[/green]")      │
│   479                                                                                            │
│                                                                                                  │
│ ┌─────────────────────────────────────────── locals ───────────────────────────────────────────┐ │
│ │            args = Namespace(input='https://btk-cdn01.cinema8.com/hls/content/entry/data/0/3… │ │
│ │                   output='merged.ts', cleanup=True, max_quality=False, verbose=False,        │ │
│ │                   baseurl=None, threads=5, chunk_size=1024, headers=None, decrypt=True,      │ │
│ │                   key_iv=None, proxy_address=None, ffmpeg_path='ffmpeg',                     │ │
│ │                   tempdir='temptsfiles', retry_count=10, timeout=5, pre_select=None)         │ │
│ │           check = False                                                                      │ │
│ │ m3u8_downloader = <vsdownload.commands.save.ProcessM3U8 object at 0x00000193A9964340>        │ │
│ │    parsed_links = (                                                                          │ │
│ │                   │                                                                          │ │
│ │                   'https://btk-cdn01.cinema8.com/hls/content/entry/data/0/38/0_htzs22hi_0_l… │ │
│ │                   │   None                                                                   │ │
│ │                   )                                                                          │ │
│ │        segments = [                                                                          │ │
│ │                   │   <m3u8.model.Segment object at 0x00000193A9964C10>,                     │ │
│ │                   │   <m3u8.model.Segment object at 0x00000193A9964820>,                     │ │
│ │                   │   <m3u8.model.Segment object at 0x00000193A9964E20>,                     │ │
│ │                   │   <m3u8.model.Segment object at 0x00000193A9964D60>,                     │ │
│ │                   │   <m3u8.model.Segment object at 0x00000193A9964D00>,                     │ │
│ │                   │   <m3u8.model.Segment object at 0x00000193A9964D30>,                     │ │
│ │                   │   <m3u8.model.Segment object at 0x00000193A9964EE0>,                     │ │
│ │                   │   <m3u8.model.Segment object at 0x00000193A9964DC0>,                     │ │
│ │                   │   <m3u8.model.Segment object at 0x00000193A9964CA0>,                     │ │
│ │                   │   <m3u8.model.Segment object at 0x00000193A9964E80>,                     │ │
│ │                   │   ... +43                                                                │ │
│ │                   ]                                                                          │ │
│ └──────────────────────────────────────────────────────────────────────────────────────────────┘ │
│                                                                                                  │
│ C:\Users\ATES-PC\anaconda3\lib\site-packages\vsdownload\commands\save.py:232 in                  │
│ download_in_mutiple_thread                                                                       │
│                                                                                                  │
│   229 │   │   │   │   │   │   "uri": utils.find_absolute_uri(parsed_links[1], segment),          │
│   230 │   │   │   │   │   │   "byterange": segment.byterange,                                    │
│   231 │   │   │   │   │   │   "key": self._find_key(parsed_links[1], segment),                   │
│ > 232 │   │   │   │   │   │   "iv": self._find_iv(segment),                                      │
│   233 │   │   │   │   │   │   "index": processed_ts_index,                                       │
│   234 │   │   │   │   │   │   "retrycount": 0                                                    │
│   235 │   │   │   │   │   }                                                                      │
│                                                                                                  │
│ ┌─────────────────────────────────────────── locals ───────────────────────────────────────────┐ │
│ │           executor = <concurrent.futures.thread.ThreadPoolExecutor object at                 │ │
│ │                      0x00000193A9964C70>                                                     │ │
│ │       parsed_links = (                                                                       │ │
│ │                      │                                                                       │ │
│ │                      'https://btk-cdn01.cinema8.com/hls/content/entry/data/0/38/0_htzs22hi_… │ │
│ │                      │   None                                                                │ │
│ │                      )                                                                       │ │
│ │ processed_ts_index = 1                                                                       │ │
│ │            segment = <m3u8.model.Segment object at 0x00000193A9964C10>                       │ │
│ │           segments = [                                                                       │ │
│ │                      │   <m3u8.model.Segment object at 0x00000193A9964C10>,                  │ │
│ │                      │   <m3u8.model.Segment object at 0x00000193A9964820>,                  │ │
│ │                      │   <m3u8.model.Segment object at 0x00000193A9964E20>,                  │ │
│ │                      │   <m3u8.model.Segment object at 0x00000193A9964D60>,                  │ │
│ │                      │   <m3u8.model.Segment object at 0x00000193A9964D00>,                  │ │
│ │                      │   <m3u8.model.Segment object at 0x00000193A9964D30>,                  │ │
│ │                      │   <m3u8.model.Segment object at 0x00000193A9964EE0>,                  │ │
│ │                      │   <m3u8.model.Segment object at 0x00000193A9964DC0>,                  │ │
│ │                      │   <m3u8.model.Segment object at 0x00000193A9964CA0>,                  │ │
│ │                      │   <m3u8.model.Segment object at 0x00000193A9964E80>,                  │ │
│ │                      │   ... +43                                                             │ │
│ │                      ]                                                                       │ │
│ │               self = <vsdownload.commands.save.ProcessM3U8 object at 0x00000193A9964340>     │ │
│ └──────────────────────────────────────────────────────────────────────────────────────────────┘ │
│                                                                                                  │
│ C:\Users\ATES-PC\anaconda3\lib\site-packages\vsdownload\commands\save.py:283 in _find_iv         │
│                                                                                                  │
│   280 │   │   │   return str(iv) or None                                                         │
│   281 │   │                                                                                      │
│   282 │   │   if segment.key is not None:                                                        │
│ > 283 │   │   │   return segment.key.iv.replace("0x", "")                                        │
│   284 │   │   else:                                                                              │
│   285 │   │   │   return None                                                                    │
│   286                                                                                            │
│                                                                                                  │
│ ┌─────────────────────────────────── locals ────────────────────────────────────┐                │
│ │ segment = <m3u8.model.Segment object at 0x00000193A9964C10>                   │                │
│ │    self = <vsdownload.commands.save.ProcessM3U8 object at 0x00000193A9964340> │                │
│ └───────────────────────────────────────────────────────────────────────────────┘                │
└──────────────────────────────────────────────────────────────────────────────────────────────────┘
AttributeError: 'NoneType' object has no attribute 'replace'

**Comment by clitic** [comment]
[vsdownload](https://github.com/clitic/vsdownload) is deprecated please use https://github.com/clitic/vsd instead.
